sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  redis:
    host: 101.201.238.8
    port: 6379
    password: 123456
    database: 10
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tEBRYciTpkz95GU1ycw
    access-key-secret: pRUmHg2mpWIRc6aBm4P2UjH1RKMrj9
    bucket-name: guli-1018
  wechat:
    appid: wxce3f7beca1cb4de9
    secret: 52e443e86386326f1807249ccdc6af09
